### PR TITLE
app: wait one tick before setNewOriginalImage

### PR DESCRIPTION
**Pull request by pulsejet**
This works around a bug in react (more details in inline comments).

Just want to make a note here that I've tested this extensively and it solves many unexpected issues (also took a very long time to debug this!)

### CODE REVIEW

**Comment by pulsejet** [comment]
@AhmeeedMostafa

**Comment by AhmeeedMostafa** [comment]
@pulsejet could u please explain what the bug is exactly, as it is not clear

**Comment by pulsejet** [comment]
@AhmeeedMostafa there's a bug in react apparently, that doesn't clean up some references during the first tick. Don't have time to fix react itself, unfortunately :(

**Comment by AhmeeedMostafa** [comment]
> @AhmeeedMostafa there's a bug in react apparently, that doesn't clean up some references during the first tick. Don't have time to fix react itself, unfortunately :(

Could u please provide some example production steps about the issue, or attach the react issue's url?

**Comment by pulsejet** [comment]
Here: https://codepen.io/pulsejet/pen/gOBQobe

Here's a video of the steps to reproduce below (in order): https://youtu.be/iUFmuV5YIG4

(reload the browser **with cache disabled** before each test).
Also since codepen uses iframe this doesn't work in incognito. Tested on latest Chrome/Firefox on Windows 11.

Test 1:
   `CREATE WITH LINK`: Works fine.
Test 2:
  `CREATE WITH ELEM`, then `DESTROY`, then `CREATE WITH ELEM` again => broken
Test 3:
  `CREATE WITH ELEM WITH DELAY`, then `DESTROY`, then `CREATE WITH ELEM WITH DELAY` again => works now (this PR has the equivalent effect)

@AhmeeedMostafa

**Review by AhmeeedMostafa — APPROVED** [review]

**Pull request merged**
