### PR TITLE
Fix filters image ratio display

### LINKED ISSUE #253: Filters list do not preserve image ratio
image

It seems the canva size is capped https://github.com/scaleflex/filerobot-image-editor/blob/e1fb6f0b467f0fafffaae56f471cb03a9b5eb580/packages/react-filerobot-image-editor/src/components/tools/Filters/FilterItem.jsx#L13-L14
Maybe it will be worth using a square canvas and containing the image  within?

Or use the current image ratio. Might be a bit more tricky if the user edit the image size/crops the image

## Context
Using latest `filerobot-image-editor version@^4.3.1`

### PR DESCRIPTION
**Pull request by skjnldsv**
| Before | After |
|:---------:|:------:|
|Peek 17-08-2022 18-04|Peek 17-08-2022 18-03|

Fix #253 
Fix https://github.com/nextcloud/viewer/issues/1335

### CODE REVIEW

**Review by CronosUnder — APPROVED** [review]

**Comment by amrelbialy** [comment]
Hey @skjnldsv, We don't consider this as a bug as it was implemented this way. The filters don't need to be aligned with image ratio as we are showing small fixed preview and when you click on any filter you can see the correct ration of the image with correct filter.

**Comment by skjnldsv** [comment]
@amrelbialy squashing the images preview is not a bug to you?
This makes this UI looks broken. If you're showing a preview, make sure you're keeping its ratio, no?
I'm also fine if you prefer to crop the image into a square. But squashing and changing the image ratio is definitely not acceptable I think :wink: 

> We don't consider this as a bug as it was implemented this way

We could say that to literally all bugs existing in the world :grin:

**Comment by skjnldsv** [comment]
Here is a more realistic example
image

**Review by ChristophWurst — APPROVED** [review]

**Review by nimishavijay — APPROVED** [review]
Agreed with @skjnldsv, cropping the image for a preview is okay, but warping it may give a wrong impression of what the filter would do :) a cropped square preview would be useful when there are multiple aspect ratios in a row, but since all the previews are of the same image, we don't have to crop it either. So nice work @skjnldsv :)

**Review by AhmeeedMostafa — APPROVED** [review]

**Review by AhmeeedMostafa — COMMENTED** [review]
Code is approved but after reviewing the PR's UI & Behavior it's better to replace with center cropping behavior for aligning UI dimensions in all cases considering small & large screens.

**Pull request closed without merging**
