### PR TITLE
Enhance Modal accessibility

### PR DESCRIPTION
**Pull request by lordofweb**
This pull request improves the accessibility of the Modal component in the filerobot-image-editor library. The changes address issues with keyboard navigation and screen reader compatibility, especially when the library is used within other modal contexts. 

The save form field could notably be inaccessible in the context of another modal

Changes made:

1. Added `role="dialog"` to the modal container to properly identify it as a dialog for assistive technologies.
2. Implemented `aria-modal="true"` to indicate that the dialog is modal.
3. Added `aria-label={title}` to provide a descriptive label for the modal, improving screen reader context.
4. Set `tabindex="-1"` on the modal container to allow it to receive focus programmatically.
5. Enhanced keyboard support by adding an 'Escape' key handler to close the modal.

These modifications significantly improve the accessibility of the Modal component, ensuring that users relying on keyboard navigation and screen readers can interact more effectively with the image editor's features.

Testing:
- Verified that the modal can be closed using the 'Escape' key.
- Checked that screen readers correctly announce the modal and its title.
- Ensured that the modal can receive focus when opened.

These changes provide a foundation for better accessibility. Future improvements could include focus management within the modal and ensuring a logical tab order.

Please review and let me know if any further changes or clarifications are needed.

## Summary by CodeRabbit

- **New Features**
  - Enhanced keyboard interaction for the modal, allowing users to dismiss it with the 'Escape' key.

- **Accessibility Improvements**
  - Added accessibility attributes to the modal, including `role`, `tabIndex`, `aria-modal`, and `aria-label`, improving support for assistive technologies.

### CODE REVIEW

**Comment by lordofweb** [comment]
@coderabbitai full review

**Comment by lordofweb** [comment]
@coderabbitai review

**Comment by lordofweb** [comment]
@coderabbitai resolve

**Review by AhmeeedMostafa — APPROVED** [review]

**Comment by AhmeeedMostafa** [comment]
Thanks @lordofweb It'll be considered in the upcoming version.

**Pull request merged**
